import os
import sys
import shutil
import tempfile
import json
from typing import Optional

from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import PlainTextResponse

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from huggingface_hub import snapshot_download

from agent.router import classify_task, check_input_compatibility, TaskType
from agent.tool_registry import list_registry_summary
from agent.gemini_client import (
    ask_gemini,
    ask_gemini_grounding,
    ask_gemini_change,
    ask_gemini_fusion,
)
from agent.audit_log import log_step, read_trail
from inference.rs_inference import RSClassifier
from inference.grounding_engine import ground_region
from inference.change_engine import detect_changes
from inference.sar_fusion_engine import fuse_optical_sar

app = FastAPI(title="SatQuery AI")

HF_REPO_ID = os.environ.get("HF_REPO_ID", "KowhickMaran/rs-eurosat-classifier")
MODEL_DIR = os.environ.get("RS_MODEL_DIR", os.path.join(os.path.dirname(__file__), "..", "models", "rs-eurosat-classifier"))
CUSTOM_CHECKPOINT = os.environ.get("RS_CHECKPOINT_PATH")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend")

_classifier = None


def ensure_model_downloaded():
    if CUSTOM_CHECKPOINT and os.path.exists(CUSTOM_CHECKPOINT):
        return CUSTOM_CHECKPOINT
    checkpoint_path = os.path.join(MODEL_DIR, "rs_classifier.pt")
    if not os.path.exists(checkpoint_path):
        snapshot_download(repo_id=HF_REPO_ID, local_dir=MODEL_DIR)
    return checkpoint_path


def get_classifier():
    global _classifier
    if _classifier is None:
        checkpoint_path = ensure_model_downloaded()
        _classifier = RSClassifier(checkpoint_path)
    return _classifier


@app.get("/health")
def health_check():
    return {
        "status": "ok",
        "service": "SatQuery AI",
        "capabilities": [
            "single_image_vqa",
            "single_image_grounding",
            "bi_temporal_change",
            "cross_modal_sar_optical",
        ],
    }


@app.get("/tools")
def get_tools_registry():
    return {"registry": list_registry_summary()}


@app.get("/audit-trail")
def get_audit_trail():
    return {"entries": read_trail()}


@app.get("/download-report")
def export_audit_report():
    trail = read_trail(limit=100)
    report_lines = [
        "# SatQuery AI - Audited Execution Report",
        f"Total Logged Steps: {len(trail)}",
        "Generated By: SatQuery AI Agentic Controller",
        "--------------------------------------------------\n",
    ]
    for idx, item in enumerate(trail, 1):
        report_lines.append(f"### Step {idx}: {item.get('step')} ({item.get('timestamp')})")
        report_lines.append("```json")
        report_lines.append(json.dumps(item.get("details", {}), indent=2))
        report_lines.append("```\n")
    
    return PlainTextResponse("\n".join(report_lines), media_type="text/markdown")


@app.post("/analyze")
async def analyze(
    question: str = Form(...),
    image: UploadFile = File(...),
    image2: Optional[UploadFile] = File(None),
    task_hint: Optional[str] = Form(None),
):
    filenames = [image.filename]
    num_images = 1
    if image2 is not None and image2.filename:
        filenames.append(image2.filename)
        num_images = 2

    compat = check_input_compatibility(filenames)
    if not compat["is_valid"]:
        raise HTTPException(status_code=400, detail=f"Input validation error: {compat['errors']}")

    task, tools_selected = classify_task(question, num_images, task_hint)

    suffix1 = os.path.splitext(image.filename)[1] or ".png"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix1) as tmp1:
        shutil.copyfileobj(image.file, tmp1)
        tmp1_path = tmp1.name

    tmp2_path = None
    if num_images == 2:
        suffix2 = os.path.splitext(image2.filename)[1] or ".png"
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix2) as tmp2:
            shutil.copyfileobj(image2.file, tmp2)
            tmp2_path = tmp2.name

    try:
        if task == TaskType.BI_TEMPORAL_CHANGE and tmp2_path:
            change_result = detect_changes(tmp1_path, tmp2_path, question)
            log_step("specialist_tool_execution", {
                "tool": "change_detector",
                "metrics": change_result,
            })

            answer = ask_gemini_change(question, change_result)
            log_step("gemini_reasoning_synthesis", {"question": question, "answer": answer})

            return {
                "task_type": task.value,
                "answer": answer,
                "specialist_result": change_result,
                "visual_evidence_b64": change_result.get("visual_evidence_b64"),
                "tools_executed": tools_selected,
            }

        elif task == TaskType.CROSS_MODAL_SAR_OPTICAL and tmp2_path:
            fusion_result = fuse_optical_sar(tmp1_path, tmp2_path, question)
            log_step("specialist_tool_execution", {
                "tool": "sar_optical_fusion",
                "metrics": fusion_result,
            })

            answer = ask_gemini_fusion(question, fusion_result)
            log_step("gemini_reasoning_synthesis", {"question": question, "answer": answer})

            return {
                "task_type": task.value,
                "answer": answer,
                "specialist_result": fusion_result,
                "visual_evidence_b64": fusion_result.get("visual_evidence_b64"),
                "tools_executed": tools_selected,
            }

        elif task == TaskType.SINGLE_IMAGE_GROUNDING:
            classifier = get_classifier()
            clf_result = classifier.predict(tmp1_path)
            ground_result = ground_region(tmp1_path, question)

            log_step("specialist_tool_execution", {
                "tools": ["rs_classifier", "region_grounder"],
                "classifier_output": clf_result,
                "grounding_output": {
                    "target_class": ground_result["target_class"],
                    "coverage": ground_result["coverage_percentage"],
                    "location": ground_result["spatial_location"],
                },
            })

            answer = ask_gemini_grounding(question, ground_result, clf_result)
            log_step("gemini_reasoning_synthesis", {"question": question, "answer": answer})

            return {
                "task_type": task.value,
                "answer": answer,
                "specialist_result": clf_result,
                "grounding_result": ground_result,
                "visual_evidence_b64": ground_result.get("visual_evidence_b64"),
                "tools_executed": tools_selected,
            }

        else:
            classifier = get_classifier()
            clf_result = classifier.predict(tmp1_path)
            log_step("specialist_tool_execution", {
                "tool": "rs_classifier",
                "result": clf_result,
            })

            answer = ask_gemini(question, clf_result)
            log_step("gemini_reasoning_synthesis", {"question": question, "answer": answer})

            return {
                "task_type": task.value,
                "answer": answer,
                "specialist_result": clf_result,
                "tools_executed": tools_selected,
            }

    finally:
        if os.path.exists(tmp1_path):
            os.remove(tmp1_path)
        if tmp2_path and os.path.exists(tmp2_path):
            os.remove(tmp2_path)


if os.path.exists(FRONTEND_DIR):
    app.mount("/app", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend_app")
    app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend_root")
